apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.appname }}
    environment: {{ .Release.Namespace }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        environment: {{ .Release.Namespace }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        livenessProbe:
          initialDelaySeconds: 70
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        resources:
          limits:
            cpu: {{ .Values.resources.cpuLimit }}
            memory: {{ .Values.resources.memLimit }}
          requests:
            cpu: {{ .Values.resources.cpuRequest }}
            memory: {{ .Values.resources.memRequest }}